import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const normalizeRisk = (riskLevel) => String(riskLevel || "LOW").toUpperCase();

const formatDate = (value) => {
  if (!value) {
    return "N/A";
  }

  const parsedDate = new Date(value);

  if (Number.isNaN(parsedDate.getTime())) {
    return String(value);
  }

  return parsedDate.toISOString().split("T")[0];
};

export const generatePdfReport = async (scanData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 40,
        size: "A4",
      });

      const fileName = `${scanData.brand}-report-${Date.now()}.pdf`;
      const reportsDir = path.join(__dirname, "../reports");
      const filePath = path.join(reportsDir, fileName);

      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      const domains = Array.isArray(scanData.domains) ? scanData.domains : [];
      const total = domains.length;
      const high = domains.filter((d) => normalizeRisk(d.risk_level) === "HIGH").length;
      const medium = domains.filter((d) => normalizeRisk(d.risk_level) === "MEDIUM").length;
      const critical = domains.filter((d) => normalizeRisk(d.risk_level) === "CRITICAL").length;

      doc.fontSize(20).text("BrandShield Report", { align: "center" });
      doc.moveDown();

      doc.fontSize(12).text(`Brand: ${scanData.brand || "N/A"}`);
      doc.text(`Scan Date: ${formatDate(scanData.scanDate)}`);
      doc.text(`Total Domains: ${total}`);
      doc.text(`High Risk: ${high}`);
      doc.text(`Medium Risk: ${medium}`);
      doc.text(`Critical Risk: ${critical}`);
      doc.moveDown();

      domains.forEach((domain, index) => {
        const score = domain.impersonation_score ?? domain.score ?? "N/A";
        const owner = domain.owner || domain.registrar || "Unknown";
        const age = typeof domain.ageInDays === "number" ? `${domain.ageInDays} days` : "N/A";
        const recommendations = Array.isArray(domain.recommendations)
          ? domain.recommendations.join(", ")
          : "N/A";

        doc.fontSize(11).text(
          `${index + 1}. ${domain.domain || "N/A"} | Score: ${score} | Risk: ${normalizeRisk(domain.risk_level)}`,
        );
        doc.text(
          `Owner: ${owner} | Created: ${formatDate(domain.createdAt)} | Age: ${age} | DNS: ${domain.dns_exists ? "Active" : "Inactive"}`,
        );
        doc.text(
          `Privacy: ${domain.isPrivacyProtected ? "Protected" : "Public"} | Registrar: ${domain.registrar || "Unknown"}`,
        );
        doc.text(`Recommendations: ${recommendations}`);
        doc.moveDown(0.6);
      });

      doc.text("Generated by BrandShield", { align: "center" });
      doc.end();

      stream.on("finish", () => resolve({ fileName, filePath }));
      stream.on("error", (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
};
