import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

// __dirname for ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const generatePdfReport = async (scanData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument();

      // file path
      const fileName = `${scanData.brand}-report-${Date.now()}.pdf`;
      const reportsDir = path.join(__dirname, "../reports");
      const filePath = path.join(reportsDir, fileName);

      // ensure folder exists
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      const stream = fs.createWriteStream(filePath);
      doc.pipe(stream);

      // HEADER
      doc.fontSize(20).text("BrandShield Report", { align: "center" });
      doc.moveDown();

      doc.fontSize(14).text(`Brand: ${scanData.brand}`);
      doc.text(`Scan Date: ${scanData.scanDate}`);
      doc.moveDown();

      // SUMMARY
      const total = scanData.domains.length;
      const high = scanData.domains.filter(
        (d) => d.risk_level === "High",
      ).length;
      const critical = scanData.domains.filter(
        (d) => d.risk_level === "Critical",
      ).length;

      doc.text(`Total Domains: ${total}`);
      doc.text(`High Risk: ${high}`);
      doc.text(`Critical Risk: ${critical}`);
      doc.moveDown();

      // TABLE HEADER
      doc.fontSize(12).text("Domain        Score        Risk");
      doc.moveDown();

      // TABLE DATA
      scanData.domains.forEach((d) => {
        doc.text(`${d.domain}     ${d.score}     ${d.risk_level}`);
      });

      doc.moveDown();

      // FOOTER
      doc.text("Generated by BrandShield", { align: "center" });

      doc.end();

      stream.on("finish", () => resolve(filePath));
      stream.on("error", (err) => reject(err));
    } catch (err) {
      reject(err);
    }
  });
};
