import mongoose from "mongoose";

const scanSchema = new mongoose.Schema(
  {
    // Original domain provided by the user
    original_domain: {
      type: String,
      required: [true, "Original domain is required"],
      unique: true,
      trim: true,
      lowercase: true,
    },

    // Domain generated by the system based on similarity logic
    generated_domain: {
      type: String,
      required: [false, "Generated domain is required"],
      trim: true,
      lowercase: true,
    },

    // Similarity percentage between original and generated domain (0-100)
    similarity_score: {
      type: Number,
      required: [false, "Similarity score is required"],
      min: [0, "Similarity score cannot be negative"],
      max: [100, "Similarity score cannot exceed 100"],
    },

    // Flag to indicate whether the generated domain exists in DNS
    dns_exists: {
      type: Boolean,
      required: [false, "DNS exists field is required"],
      default: false,
    },
  },
  {
    // Automatically adds createdAt and updatedAt fields
    timestamps: true,
  },
);

const Scan = mongoose.model("Scan", scanSchema);

export default Scan;
